### ISSUE TITLE
Add compilation instructions

### ISSUE THREAD

**Issue by livphi** [Treer/amidstest#42]
Could you add instructions for how to compile Amidst for Minetest? Minetest's source code is a good example. https://github.com/minetest/minetest/blob/master/doc/compiling/linux.md Here's an example from a project written in java. https://github.com/bisq-network/bisq/blob/master/docs/build.md
I tried using `mvn compile` but I ran into errors. Maven couldn't find the dependency `jnbt:jnbt:jar:1.3`. I tried commenting out the jnbt dependency and everything worked except for the files in `src/main/java/amidst/mojangapi/`. If this is for Minetest why would it need to use the mojang api? Removing the mojangapi directory didn't work either. I prefer to compile from the terminal.

**Comment by Treer** [comment]
There's a github action that will compile it for you.

Alternately, you could use the action's [script](https://github.com/Treer/Amidst-for-Minetest/blob/master/.github/workflows/build.yml) as a guide for the steps to manually compile it.

The action will trigger any time I push something to the `master` branch or the `github_actions` branch, so if you were to fork this repository, your github account will build you a copy each time you make a change.

At least... I think does, it's been a long time since I used it and the actions feature keeps changing. Three weeks ago @DragonWrangler1 forked it and started working on [their own action script](https://github.com/DragonWrangler1/Amidst-for-Minetest/commits/master/), which I haven't looked at so I don't know what it's for - it's possible the action script doesn't work any more and they are trying to fix it. 

(I was going to wait until they had theirs working before looking into it, and then see if anything needed updating here and whether the Gson issue could be fixed again, though they seem to have stopped)

Edit: DragonWrangler1's script is no longer accessible

>  If this is for Minetest why would it need to use the mojang api?

It used to be able to do both Minecraft and Minetest worlds, long story. The Minecraft features are disabled now.

**Comment by DragonWrangler1** [comment]
> At least... I think does, it's been a long time since I used it and the actions feature keeps changing. Three weeks ago @DragonWrangler1 forked it and started working on [their own action script](https://github.com/DragonWrangler1/Amidst-for-Minetest/commits/master/), which I haven't looked at so I don't know what it's for - it's possible the action script doesn't work any more and they are trying to fix it.
> 
> (I was going to wait until they had theirs working before looking into it, and then see if anything needed updating here and whether the Gson issue could be fixed again, though they seem to have stopped)

Ya. I've been busy working on other things.

**Comment by livphi** [comment]
https://github.com/toolbox4minecraft/amidst/wiki/Building-from-Source-Code I found it. Oops.
Run it with `java -jar target/amidst-minetest-v1-4-3.jar`
