### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by KCoombes67** [Treer/amidstest#5]
Solved

**Comment by Treer** [comment]
Sorry, what was this?

It was solved before I saw it, was it anything that might affect/help other people?

**Comment by KCoombes67** [comment]
Only if they attempt to add additional biome files by editing an existing one - your program does not recognize any but the standard 4 files that came with it. I forgot to remove the edited file from the biome folder before running Amidst, and it errored out. Removing the edited file fixed the load error.

**Comment by Treer** [comment]
Editing an existing biome file should work, there must be an error in the file. I'll make up some bad files and try to make sure the error is better handled.

It's not limited to the 4 standard files.

**Comment by Treer** [comment]
If you still have the edited biome file, I'd be curious to see it - to check what the formatting issue was and whether it can be handled better.

**Comment by Treer** [comment]
I think your reply/attachment was lost - try replying directly on github rather than via email.

**Comment by KCoombes67** [comment]
[Haven for Amidst.zip](https://github.com/Treer/amidstest/files/1956933/Haven.for.Amidst.zip)
wouldn't let me attach as MT file, so zipped

**Comment by Treer** [comment]
Thanks for that. The latest version of Amidstest will read your Haven file now.

FWIW the problem was a comma after the last biome in the list - at the end of line 23. It was creating an empty biome at the end of the list.

When you're happy with `Haven for Amidst.mt`, would you be interested in [adding it to the wiki](https://github.com/Treer/amidstest/wiki/Get-or-share-more-biome-profiles) with a link or description about what Haven is? (unless Haven is something private)

**Comment by KCoombes67** [comment]
Ironically, I have the same problem when coding mods :) I'd be happy to add to your wiki, if I ever get Haven up and running. I plan to use Amidst to save myself a ton of time finding a nice mapseed.

**Comment by Treer** [comment]
A haunted biome sounds very intriguing/flavoursome.

**Comment by KCoombes67** [comment]
I plan to add night-spawning mobs to that biome - perhaps with rare item drops
